#!/bin/bash

if [[ $* == *--help* ]] ; then
	cat $PWD/README.txt
else
	mkdir -p $PWD/$1/tests
	mkdir -p $PWD/$1/examples
	echo ' Usage: '$1' [arguments]' > $PWD/$1/README.txt
	cat examples/READMEexample.txt >> $PWD/$1/README.txt
	cat examples/SCRIPTexample.txt > $PWD/$1/$1
	echo $1 ' has been created'
	chmod +x $PWD/$1/$1
fi
